DROP DATABASE IF EXISTS epytodo;
CREATE DATABASE epytodo;

USE epytodo;

DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS todo;

CREATE TABLE IF NOT EXISTS user (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
);

ALTER TABLE user ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS todo (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT NOW(),
    due_time DATETIME NOT NULL,
    status varchar(11) NOT NULL DEFAULT,
    user_id INT UNSIGNED NOT NULL,
    CONSTRAINT fk_id
        FOREIGN KEY (user_id)
        REFERENCES user(id),
    PRIMARY KEY (id)
);

ALTER TABLE todo ENGINE = InnoDB;
